server:
  port: 8082

spring:
  application:
    name: enrollment-service
  datasource:
    url: jdbc:h2:mem:enrollments-db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        loggerLevel: FULL

resilience4j:
  circuitbreaker:
    instances:
      students:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - "feign.FeignException$NotFound"
  retry:
    instances:
      students:
        maxAttempts: 3
        waitDuration: 300ms
        retryExceptions:
          - feign.RetryableException

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    rs.ac.imievent.enrollment: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.openfeign: DEBUG
