server:
  port: 8081

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:h2:mem:students-db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    rs.ac.imievent.students: DEBUG
